import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import BoostrapInstall from "./components/bootstrap";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Upload SEB file for assessment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
